### ISSUE TITLE
Understanding csv outputs

### ISSUE THREAD

**Issue by ademasi** [timoll/bag_scrape#1]
Thank you for those useful python scripts.

I am having some trouble with the generated CSVs.  I am not sure if the issue is coming from the script or from the BAG data, or my understanding of boths.

If I sum the number of case from /out/ch_cantons/cases.csv for 2020-08-02, I get 46.0 (`df.loc["2020-08-02"].sum() ` . The BAG said yesterday that there was [138 new cases ](https://twitter.com/BAG_OFSP_UFSP/status/1289868669015732224) on that same day.

**Comment by timoll** [comment]
There is a difference in case date and reporting date. Yesterday the BAG reported 138 cases, but only 46 where from Saturday.

You would have to compare the output from tag 2020-08-03 with the output from tag 2020-08-02 to see which canton had new cases for which date.

I hope that helps.

**Comment by ademasi** [comment]
Ha okay, thank you, yes it helps :smiley: 

I did not know there were computing the number that way.
